### PR TITLE
Formatter & enter handler

### PR DESCRIPTION
**Pull request by wyozi**

### CODE REVIEW

**Comment by wyozi** [comment]
I have to say that the current AST (or Psi?) tree isn't perfect for formatting purposes. For example there are two Psi nodes I found that should be indented; Struct declarations and compound statements. There might be more but those two seemed to catch most of the blocks I threw at it.

Also the formatter as is does not format single-statement if statements (eg. `if (x) doY()`) properly. I'm not sure how to solve that, because the if condition and body is all stored within the same if Psi node,

**Comment by Gustl22** [comment]
Does this feature work and can we integrate it @Darkyenus ?

**Comment by Darkyenus** [comment]
I don't know yet, I don't have much time to devote to this plugin. But I'll try to look into it.

**Comment by Gustl22** [comment]
Ok thanks :)

**Comment by Darkyenus** [comment]
Merged (manually with [extra commit](729b32e1f36a2285b1fb4afa85816d7f7aade9fc) which fixed a soft merge conflict, and that seems to have tripped up GitHub).

**Comment by Gustl22** [comment]
Works nice :) Thanks @wyozi, too.

**Pull request closed without merging**
