### PR TITLE
Add CStyle constructor inspection

### PR DESCRIPTION
**Pull request by wyozi**
Adds warning for CStyle struct constructors.

Nvidia GLSL compiler (or at least one version of it) rejects them.

### CODE REVIEW

**Comment by wyozi** [comment]
Just realized this will not work if c-style constructor has multiple arguments. Will fix shortly.

**Comment by wyozi** [comment]
I fixed multiple arguments, added a few tests and prevented inspection for array/non-struct types. The spec allows vector construction using C-style constructors in version 430 (checked with glslangValidator), so I decided to disable all non-struct types. 

Inspection still fails for C-style constructors inside array bracket constructor `Light[] l = { {v} };`)

**Comment by Darkyenus** [comment]
First off, thanks for the PRs!

The spec allows this (at least in 4.50) so I am not sure if it should be enabled by default and as a warning.
I like the idea of "convert constructor to initializer and vice versa" quick fix (regardless of the warning), but I'd add the warning only for files whose version is low enough to be actually wrong. Determining the version is not yet implemented though, so it would have to wait for that.

**Comment by wyozi** [comment]
Oh yeah, I tried initializer list construction of a struct in the reference compiler but did not realize it requires 4.50. #40 is needed for this for sure.

**Pull request closed without merging**
