### PR TITLE
Array overhaul

### PR DESCRIPTION
**Pull request by Darkyenus**
This PR changes the way GLSLArrayType works and many things around it. It is still not fully comprehensive and there are still things to improve, but this is the first step.

Notable changes:
- Adds support for parsing (and knowing about) multidimensional arrays
- Inferring array dimension size from initializer list (= 'int[] foo = {3,4};' -> foo is int[2]) (inferring from other assignments (array constructors, existing arrays, etc.) will come later)
- Small changes and fixes (see commit logs and commits themselves)

What will follow:
- As noted above, improved array size inferring
- Some sort of basic constant expression analysis. Right now, it doesn't even recognize literals, so it treats `int[3]` as array of unknown size.
- Some annotators for arrays (size validation (positive integer), initializer list typechecking (arrays, vectors, structs), ...)

### CODE REVIEW

**Comment by Darkyenus** [comment]
In commits after merge:
- Constructors were previously handled like function calls, now there is a distinction (GLSLConstructorExpression)
- Array size can now be inferred from initializer even if the initializer is an expression (usually constructor or assignment)

**Comment by AbigailBuccaneer** [comment]
Would it be cleaner to parse and refer to eg. an int[2][2] as an array of 2 (array of 2 ints)? That is, a GLSLArrayType should be single-dimensional, and multidimensional arrays should have a nested array type.

**Comment by Darkyenus** [comment]
I don't think it would be necessarily cleaner to parse, but it might be easier to work with in some cases. So far I haven't had any problems with this approach, but I'll look into it (probably as a different PR to not create unnecessary git complexity).

**Comment by AbigailBuccaneer** [comment]
Fair enough. This looks good to merge then.

**Comment by AbigailBuccaneer** [comment]
Hmm, I just stumbled across the line in the GLSL 4.5 spec:

```
float[2][3] // an array of size [2][3] of float, not size [3] of float[2]
```

So the current method is more in keeping with the spec. (I'm not sure in what way this affects anything.)

**Comment by Darkyenus** [comment]
Yay, less work. But seriously, I don't think that there is any particular advantage in using one approach over the other. It would not be hard to change, but I don't think that it is needed right now. Having the dimensions in one array is useful during iterating through them (for example during array declaration).

**Pull request merged**
